# Environment
env:
  env_name: lorenz
  num_envs: 4

# collector
collector:
  frames_per_batch: 4096
  total_frames: 400_000_000
  frame_skip: 1
  max_episode_length: 400

# logger
logger:
  backend: wandb
  project_name: torchrl_ppo_lorenz
  group_name: why_are_all_the_good_names_taken_aaa
  exp_name: Lorenz_PPO_test2
  test_interval: 1000
  num_test_episodes: 20
  video: False

# Optim
optim:
  lr: 2.5e-4
  eps: 1.0e-6
  weight_decay: 0.0
  max_grad_norm: 0.5
  anneal_lr: True

# loss
loss:
  gamma: 0.9
  mini_batch_size: 1024
  ppo_epochs: 3
  gae_lambda: 0.95
  clip_epsilon: 0.1
  anneal_clip_epsilon: True
  critic_coef: 1.0
  entropy_coef: 0.01
  loss_critic_type: l2
